-- 1. Tabla de Categorías (para organizar productos)
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT NOT NULL,
  descripcion TEXT
);

-- 2. Tabla de Productos (Maneja la info y el inventario)
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio_venta NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  precio_costo NUMERIC(10, 2) DEFAULT 0.00,
  stock_actual INT NOT NULL DEFAULT 0,
  stock_minimo INT DEFAULT 0,
  sku TEXT UNIQUE,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL
);

-- 3. Tabla de Clientes (Para ventas y cotizaciones)
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT NOT NULL,
  email TEXT UNIQUE,
  telefono TEXT,
  notas_cliente TEXT
);

-- 4. Tabla de Ventas (El ticket/recibo de cada venta)
CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  total NUMERIC(10, 2) NOT NULL,
  metodo_pago TEXT NOT NULL DEFAULT 'efectivo', -- 'efectivo', 'tarjeta', etc.
  -- 'usuario_id' se vincula al usuario que hizo la venta (de Supabase Auth)
  usuario_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL
);

-- 5. Tabla 'Venta_Items' (Qué productos iban en cada venta)
-- Esta es una "tabla intermedia". Conecta Ventas y Productos.
CREATE TABLE IF NOT EXISTS venta_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad INT NOT NULL,
  -- Guarda el precio del producto AL MOMENTO de la venta
  precio_unitario NUMERIC(10, 2) NOT NULL 
);

-- 6. Tabla de Cotizaciones
CREATE TABLE IF NOT EXISTS cotizaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  tipo TEXT DEFAULT 'personalizada' CHECK (tipo IN ('personalizada', 'estandar')),
  nombre_producto TEXT, -- Para cotizaciones estándar
  total NUMERIC(10, 2) NOT NULL,
  valida_hasta DATE, -- Opcional: solo para personalizadas
  -- 'pendiente', 'aceptada', 'rechazada'
  estado TEXT NOT NULL DEFAULT 'pendiente', 
  usuario_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 7. Tabla 'Cotizacion_Items' (Qué productos iban en cada cotización)
CREATE TABLE IF NOT EXISTS cotizacion_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT NOT NULL REFERENCES cotizaciones(id) ON DELETE CASCADE,
  producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad INT NOT NULL,
  precio_unitario NUMERIC(10, 2) NOT NULL
);

-- 8. Tabla de Notas (Tu apartado de notas)
CREATE TABLE IF NOT EXISTS notas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  titulo TEXT,
  contenido TEXT NOT NULL,
  -- 'recordatorio', 'urgente', 'general'
  etiqueta TEXT DEFAULT 'general',
  usuario_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 9. Tabla de Movimientos de Inventario (¡Un extra muy útil!)
-- Para rastrear por qué cambió el stock (venta, ajuste manual, devolución)
CREATE TABLE IF NOT EXISTS movimientos_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  -- 'venta', 'ajuste', 'devolucion', 'compra_proveedor'
  tipo_movimiento TEXT NOT NULL, 
  cantidad INT NOT NULL, -- (ej. -1 por una venta, +10 por compra)
  justificacion TEXT,
  usuario_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- 10. Tabla de Ingredientes (Para cotizaciones personalizadas)
CREATE TABLE IF NOT EXISTS ingredientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT NOT NULL,
  unidad_medida TEXT DEFAULT 'kg', -- 'kg', 'gr', 'lt', 'ml', 'pz', 'taza', etc.
  precio_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  stock_actual NUMERIC(10, 2) DEFAULT 0.00,
  activo BOOLEAN DEFAULT TRUE
);

-- 11. Tabla 'Cotizacion_Ingredientes' (Ingredientes en cada cotización)
CREATE TABLE IF NOT EXISTS cotizacion_ingredientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id BIGINT NOT NULL REFERENCES cotizaciones(id) ON DELETE CASCADE,
  ingrediente_id BIGINT NOT NULL REFERENCES ingredientes(id) ON DELETE RESTRICT,
  cantidad NUMERIC(10, 2) NOT NULL,
  precio_unitario NUMERIC(10, 2) NOT NULL,
  notas TEXT
);

-- 12. Tabla de Metas (Para guardar metas diarias/mensuales)
CREATE TABLE IF NOT EXISTS metas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  tipo TEXT NOT NULL DEFAULT 'diaria' CHECK (tipo IN ('diaria', 'semanal', 'mensual')),
  monto NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  usuario_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
  UNIQUE(tipo, usuario_id)
);